version: '3.8'
services:
  api:
    image: monots/app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/app/packages/api
    command: yarn start:watch
    volumes:
      - .:/root/app
      - /root/app/node_modules/
      - /root/app/packages/api/node_modules/
      - /root/app/packages/app/node_modules/
      - /root/app/packages/shared/node_modules/
    env_file:
      - ./packages/api/local.env.list
    depends_on:
      - postgres
    ports:
      - 4000:4000
  app:
    image: monots/app
    working_dir: /root/app/packages/app
    command: 'yarn start'
    volumes:
      - .:/root/app
      - /root/app/node_modules/
      - /root/app/packages/api/node_modules/
      - /root/app/packages/app/node_modules/
      - /root/app/packages/shared/node_modules/
    depends_on:
      - api
    ports:
      - 3000:3000
  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=monots
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
